AppGaleriaWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from AppGaleriaWeb.views import * 
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.views import LogoutView



urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('index/', index, name='index'),
    path('enviar_correo/', views.enviar_correo, name='enviar_correo'),
    path('enviar_consulta_artista/', views.enviar_consulta_artista, name='enviar_consulta_artista'),
    path('artistas/',artistas),
    path('galerias/', galerias),
    path('registrarse/',registrarse),
    path('email_exitoso/',email_exitoso,name='email_exitoso'),
    path('email_fallido/',email_fallido,name='email_fallido'),
    path('contactos/',contactos),
    path('nuestros_servicios/', views.nuestros_servicios, name='nuestros_servicios'),
    path('sobre_nosotros/', sobre_nosotros, name='sobre_nosotros'),
    path('pagina_en_construccion/', pagina_en_construccion, name='pagina_en_construccion'),
    path('formularioAltaArtista/', formularioAltaArtista, name='formularioAltaArtista'),
    path('registro/', registrar, name='registro'),
    path('registro_exitoso_obra_arte/', registro_exitoso_obra_arte, name='registro_exitoso_obra_arte'),
    path('aviso_registroArtista/', aviso_registroArtista, name='aviso_registroArtista'),
    path('formularioAltaUsuario/', formularioAltaUsuario, name='formularioAltaUsuario'),
    path('formularioAltaObraArte1/', formularioAltaObraArte1, name='formularioAltaObraArte1'),
    path('formularioAltaGaleria/', formularioAltaGaleria, name='formularioAltaGaleria'),# Nueva URL para dar de alta Galerias
    path('formularioAltaCarrito/', formularioAltaCarrito, name='formularioAltaCarrito'),#Nueva URL para dar de alta los Carritos
    path('lista_artistas/', lista_artistas, name='lista_artistas'),# Nueva URL para listar los artistas
    path('lista_galerias/', lista_galerias, name='lista_galerias'),# Nueva URL para listar los galerias
    path('buscar_artista/', buscar_artista, name='buscar_artista'),# Nueva URL para Buscar los artistas
    path('consulta_artista/<int:artista_id>/', consulta_artista, name='consulta_artista'),
    path('lista_obras_galeria/<int:galeria_id>/', views.lista_obras_galeria, name='lista_obras_galeria'),
    path('detalle_obra/<int:obra_id>/', views.detalle_obra, name='detalle_obra'),
    path('detalle_obra_galeria/<int:obra_id>/', views.detalle_obra_galeria, name='detalle_obra_galeria'),
    path('obras_por_artista/<int:artista_id>/', views.obras_por_artista, name='obras_por_artista'),
    path('consulta_artista/', views.consulta_artista, name='consulta_artista'),
    path('login_view/', login_view, name='login_view'),
    path('register/', register, name='register'),
    path('logout/', LogoutView.as_view (template_name="logout.html"), name='logout'),
]   



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GaleriaVicuDesign/urls.py
from django.contrib import admin
from django.urls import path, include
from AppGaleriaWeb.views import * 
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('vicuDesign/', include('AppGaleriaWeb.urls')),
    #path('GaleriaVicuDesign/', include('AppGaleriaWeb.urls')),
    
    path('', include('AppGaleriaWeb.urls')),  # URL raíz para la aplicación
       
      
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppGaleriaWeb/models.py
from django.db import models

# Create your models here.
class Galeria(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    fechaCreacion = models.DateField()
    obras = models.ManyToManyField('ObraArte', related_name='galerias', blank=True)
    imagen = models.ImageField(upload_to='galerias/', null=True, blank=True)
    
    def __str__(self):
        return self.nombre
        
class Usuario (models.Model):
    nombreUsuario = models.CharField(max_length=50)
    apellidoUsuario = models.CharField(max_length= 60)
    edadUsuario = models.IntegerField()
    emailUsuario = models.EmailField(unique=True)
    carrito = models.OneToOneField('Carrito', on_delete=models.CASCADE, null=True, blank=True)
    
    
    def __str__(self):
        return self.nombreUsuario

class Artista (models.Model):
    nombreArtista = models.CharField(max_length=50)
    apellidoArtista = models.CharField(max_length= 60)
    nacionalidadArtista = models.CharField(max_length=50)
    emailArtista = models.EmailField(unique=True)
    imagen = models.ImageField(upload_to='artistas/', null=True, blank=True)

    def __str__(self):
        return f' {self.nombreArtista} - {self.apellidoArtista}'
    
class ObraArte(models.Model):
    titulo = models.CharField(max_length=150)
    descripcion = models.TextField()
    autor = models.ForeignKey('Artista', on_delete=models.CASCADE, related_name='obras')
    precio = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    imagen = models.ImageField()
    fechaCreacion = models.DateField()
    vendido = models.BooleanField(default=False)
    # Relación ForeignKey a Galeria
    # Una ObraArte pertenece a una Galeria
    galeria = models.ForeignKey(Galeria, on_delete=models.CASCADE)  # Cambio el on_delete a CASCADE

    def __str__(self):
        return f'Autor: {self.autor} Título: {self.titulo}'

class Carrito(models.Model):
    comprador = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='carritos')
    obras = models.ManyToManyField(ObraArte)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    
    def __str__(self):
        return f"Carrito de {self.comprador.nombreUsuario}"
    
    

AppGaleriaWeb/forms.py
from django import forms
from .models import ObraArte

class ObraArteForm(forms.ModelForm):
    class Meta:
        model = ObraArte
        fields = ['titulo', 'descripcion', 'autor', 'precio', 'imagen','fechaCreacion','vendido', 'galeria']
        

AppGaleriaWeb/views.py
from django.shortcuts import render , get_object_or_404,redirect
from django.http import HttpResponse
from .models import * 
from django.urls import path, reverse
from AppGaleriaWeb import views
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.template.loader import render_to_string
#Envio de email
from django.shortcuts import render, redirect
from django.core.mail import send_mail,EmailMessage
from django.conf import settings

# Create your views here.

def enviar_correo(request):
    if request.method == 'POST':
        nombre_completo = request.POST['nombre_completo']
        telefono = request.POST['telefono']
        email = request.POST['email']
        asunto = request.POST['asunto']
        descripcion = request.POST['descripcion']

        # Cuerpo del mensaje
        mensaje = f'Nombre: {nombre_completo}\nTeléfono: {telefono}\nEmail: {email}\nAsunto: {asunto}\nDescripción: {descripcion}'

        try:
            # Enviar correo
            send_mail(
                'Formulario de Contacto',  # Asunto del correo
                mensaje,  # Cuerpo del correo
                settings.EMAIL_HOST_USER,  # Remitente
                ['CoderPtyhonWeb2023@gmail.com'],  # Destinatario
                fail_silently=False,
            )
            return redirect('email_exitoso')  # Redirige a una página de éxito
        except Exception as e:
            # Manejo de errores (puedes personalizar esto)
            return redirect('email_fallido')  # Redirige a una página de error
    else:
        return render(request, 'contactos.html')
    

# Vista para enviar una consulta de un artista
def enviar_consulta_artista(request):
    artista_id = request.GET.get('artista_id')
    obra_id = request.GET.get('obra_id')
    
  
    artista = get_object_or_404(Artista, pk=artista_id)
    obra = get_object_or_404(ObraArte, pk=obra_id) if obra_id else None
    
    if request.method == 'POST':
        nombre_completo = request.POST['nombreCompleto']
        telefono = request.POST['telefono']
        email = request.POST['email']
        mensaje = request.POST['mensaje']

        # Dirección de correo a la que se enviará la consulta
        destinatario = artista.emailArtista  # Cambia esto a la dirección de correo real

        # Cuerpo del mensaje
        cuerpo_mensaje = f'Nombre: {nombre_completo}\nTeléfono: {telefono}\nEmail: {email}\nMensaje: {mensaje}'

        try:
            # Enviar correo
            send_mail(
                'Consulta de Artista',  # Asunto del correo
                cuerpo_mensaje,  # Cuerpo del correo
                email,  # Remitente (cambia esto)
                [destinatario],  # Destinatario
                fail_silently=False,
            )
            return render(request, 'email_exitoso.html')  # Redirige a la página de éxito
        except Exception as e:
            # Manejo de errores (puedes personalizar esto)
            return render(request, 'email_fallido.html')  # Redirige a la página de error

    return render(request, 'consulta_artista.html', {'artista': artista, 'obra': obra})




#Envio Exitoso
#Creamos la vista de Inicio
def email_exitoso(request):
    return render(request, 'email_exitoso.html')

#Email Fallido
def email_fallido(request):
    return render(request, 'email_fallido.html')


#Creamos la vista de Inicio
def index(request):
    return render(request, 'index.html')

#Creamos la vista de Inicio
def artistas(request):
    return render(request, 'artistas.html')

#Creamos la vista para Galerias
def galerias(request):
    return render(request, 'galerias.html')

#Creamos la vista para Registrarse
def registrarse(request):
    return render(request,'registrarse.html')

#Creamos la vista de Registro de usuarios
def registrar (request):
    return render(request,'registro.html')

#Creamos la vista de Aviso de Registro
def aviso_registroArtista (request):
    return render(request,'aviso_registroArtista.html')


#Creamos la vista de contactos
def contactos(request):
    return render(request,'contactos.html')

def nuestros_servicios(request):
     return render(request, 'nuestros_servicios.html')

def sobre_nosotros(request):
    return render (request, 'sobre_nosotros.html')

def pagina_en_construccion(request):
    return render (request, 'pagina_en_construccion.html')


from django.core.files.uploadedfile import InMemoryUploadedFile
def formularioAltaArtista(request):
    
    if request.method == 'POST':
        # Obtengo los datos del formulario
        nombre_artista = request.POST['nombreArtista']
        apellido_artista = request.POST['apellidoArtista']
        nacionalidad_artista = request.POST['nacionalidadArtista']
        email_artista = request.POST['emailArtista']
        #tipo = request.POST['tipo']  # Obtener el tipo de usuario
        imagen = request.FILES.get('imagen')  # Obtener el archivo de imagen
        #Creo la instancia del modelo Artista y la guarda en BD
        
        artista = Artista(
                nombreArtista=nombre_artista,
                apellidoArtista=apellido_artista,
                nacionalidadArtista=nacionalidad_artista,
                emailArtista=email_artista,
                imagen = imagen # Asignar la imagen al campo 'imagen'
            )
        artista.save()
            
        #form = formularioAltaArtista(request.POST)
        return render(request, 'index.html')  # si todo salio bien envia a págian de inicio
    
    else:
        # es una solicitud GET, mostrar de nuevo el formulario
        #return render(request,'formularioAltaArtista.html')
        return render(request, 'formularioAltaArtista.html')


#Creo la funcion para dar de alta los usuarios
def formularioAltaUsuario(request):
    if request.method == 'POST':
        # Obtengo los datos del formulario
        nombre_usuario = request.POST['nombreUsuario']
        apellido_usuario = request.POST['apellidoUsuario']
        edad_usuario = request.POST['edadUsuario']
        email_usuario = request.POST['emailUsuario']
        # Creo la instancia del modelo Usuario y la guardo en la BD
        
        usuario = Usuario(
            nombreUsuario=nombre_usuario,
            apellidoUsuario=apellido_usuario,
            edadUsuario=edad_usuario,
            emailUsuario=email_usuario
        )
        usuario.save()
        
        # Puedes mostrar un mensaje de éxito si lo deseas
        return render(request, 'index.html') 

        

    else:
        # Es una solicitud GET, mostrar el formulario
        return render(request, 'formularioAltaUsuario.html')



from django.contrib.auth.decorators import user_passes_test

# Define una función de prueba que verifica si el usuario tiene permiso para escribir en la BD
def tiene_permiso_escritura(user):
    return user.has_perm('permiso_personalizado')

#
def registro_exitoso_obra_arte(request):
    return render(request, 'registro_exitoso_obra_arte.html')


#--------------------------------------------------------------------------------------------------
from django.shortcuts import render
from .models import ObraArte, Galeria

def formularioAltaObraArte1(request):
    artistas = Artista.objects.all()
    galerias = Galeria.objects.all()
    
    if request.method == 'POST':
        # Obtén los datos del formulario
        titulo = request.POST['titulo']
        descripcion = request.POST['descripcion']
        autor_id = request.POST['autor']
        precio = request.POST['precio']
        fecha_creacion = request.POST['fechaCreacion']
        vendido = request.POST.get('vendido', False)
        imagen = request.FILES['imagen']

        # Obtén el valor de la galería desde el formulario
        galeria_id = request.POST.get('galeria', None)

        # Verifica si se ha seleccionado una galería
        if galeria_id is not None:
            try:
                galeria = Galeria.objects.get(id=galeria_id)
                obra_arte = ObraArte(
                    titulo=titulo,
                    descripcion=descripcion,
                    autor_id=autor_id,
                    precio=precio,
                    fechaCreacion=fecha_creacion,
                    vendido=vendido,
                    imagen=imagen,
                    galeria=galeria,  # Asigna la galería a la obra de arte
                )

                obra_arte.save()
                
                # Asocia la obra de arte con la galería
                galeria.obras.add(obra_arte)

                return render(request, 'registro_exitoso_obra_arte.html')
            except Galeria.DoesNotExist:
                # Manejar el caso donde la galería no existe
                return render(request, 'error.html', {'mensaje': 'La galería seleccionada no existe.'})
        else:
            # Manejar el caso donde no se selecciona una galería
            return render(request, 'error.html', {'mensaje': 'Debes seleccionar una galería.'})
    else:
        # Es una solicitud GET, muestra el formulario de alta de ObraArte
        # Debes proporcionar una lista de artistas disponibles para seleccionar el autor
        # Por ejemplo, artistas = Artista.objects.all()
        return render(request, 'formularioAltaObraArte1.html', {'artistas': artistas, 'galerias': galerias})







#Creo funcion para dar de alta la obra.

from django.shortcuts import render, redirect
from .models import ObraArte, Galeria
from .forms import ObraArteForm

def formularioAltaObraArte(request):
    artistas = Artista.objects.all() 
    galerias = Galeria.objects.all()
    obra_guardada = False  # Variable para indicar si la obra se guardó con éxito
    
    if request.method == 'POST':
        form = ObraArteForm(request.POST, request.FILES)
        if form.is_valid():
            obra_arte = form.save()
            
            # Si deseas asociar la obra de arte a una galería, puedes hacerlo aquí

AppGaleriaWeb/templates/buscar_artista.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
    <h1 class="titulo-centrado">Buscar Artista</h1>
    <ul>
       
    <form method="post">
        {% csrf_token %}
        <label for="nombre_artista">Nombre del artista:</label>
        <input type="text" name="nombre_artista" value="{{ nombre }}"><br>
        <label for="apellido_artista">Apellido del artista:</label>
        <input type="text" name="apellido_artista" value="{{ apellido }}"><br>
        <label for="nacionalidad_artista">Nacionalidad del artista:</label>
        <input type="text" name="nacionalidad_artista" value="{{ nacionalidad }}"><br>
        <label for="email_artista">Email del artista:</label>
        <input type="text" name="email_artista" value="{{ email }}"><br>
        <input type="submit" value="Buscar">
    </form>

    {% if resultados %}
        <h2>Resultados de la búsqueda:</h2>
        <ul>
            {% for artista in resultados %}
                <li>{{ artista.nombreArtista }} {{ artista.apellidoArtista }}</li>
            {% endfor %}
        </ul>
    {% elif sin_resultados %}
        <p>Registro no encontrado </p>
    {% endif %}
    </ul>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/consulta_artista.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
<div class="container">
    <h1 class="titulo-centrado">Consultas</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" action="{% url 'enviar_consulta_artista' %}?artista_id={{ artista.id }}{% if obra %}&obra_id={{ obra.id }}{% endif %}">

                {% csrf_token %}
                
                <div class="form-group">
                    <label for="nombreCompleto">Artista:</label>
                    <input type="text" class="form-control" id="nombreCompleto" value="{{ artista.nombreArtista }} {{ artista.apellidoArtista }}" readonly>
                </div>
                
                {% if obra %}
                    <div class="form-group">
                        <label for="obra">Obra:</label>
                        <input type="text" class="form-control" id="obra" value="{{ obra.titulo }}" readonly>
                    </div>
                {% endif %}
                
                <div class="form-group">
                    <label for="nombreCompleto">Nombre Completo:</label>
                    <input type="text" class="form-control" id="nombreCompleto" name="nombreCompleto" required>
                </div>
                <div class="form-group">
                    <label for="telefono">Teléfono:</label>
                    <input type="tel" class="form-control" id="telefono" name="telefono" required>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="mensaje">Mensaje:</label>
                    <textarea class="form-control" id="mensaje" name="mensaje" rows="4" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Enviar Consulta</button>
            </form>
        </div>
    </div>
</div>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/contactos.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
    <div class="formulario-contacto">
        <h1 class="titulo-centrado">Contáctanos</h1>
        <form method="post" action="{% url 'enviar_correo' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="nombre_completo">Nombre Completo:</label>
                <input type="tel" class="form-control" id="nombre_completo" name="nombre_completo">
            </div>
            <div class="form-group">
                <label for="telefono">Teléfono:</label>
                <input type="tel" class="form-control" id="telefono" name="telefono">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="asunto">Asunto:</label>
                <input type="text" class="form-control" id="asunto" name="asunto" required>
            </div>
            <div class="form-group">
                <label for="descripcion">Descripción de la consulta:</label>
                <textarea class="form-control" id="descripcion" name="descripcion" rows="4" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/detalle_obra.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
<div class="menu">
  <div class="center-content">
    <h1>Detalles de la Obra</h1>
    <a href="{{ previous_url }}" class="btn btn-primary">Volver</a>
    <h2>{{ obra.titulo }}</h2>
    <p>{{ obra.descripcion }}</p>
    <p>Artista: {{ obra.autor.nombreArtista }}</p>
    <p>Precio: {% if obra.precio %}${{ obra.precio }}{% else %}No disponible{% endif %}</p>
    <p>Fecha de Creación: {{ obra.fechaCreacion }}</p>
    {% if obra.vendido %}
      <p>Estado: Vendido</p>
    {% endif %}
    <img src="{{ obra.imagen.url }}" alt="{{ obra.titulo }}" />
  </div>
</div>
<style>
.menu {
  text-align: center; /* Centrar contenido horizontalmente */
}

.center-content {
  background-color: #fff; /* Cambia el color de fondo del contenido */
  text-align: center; /* Centra el contenido horizontalmente */
  padding: 20px; /* Agrega espaciado alrededor del contenido */
}

</style>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/detalle_obra_galeria.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
<div class="menu">
  <div class="center-content">
    <h1>Detalles de la Obra</h1>
    <!-- Verificar si la galería existe antes de mostrar el botón "Volver" -->
    {% if galeria %}
      <a href="{% url 'lista_obras_galeria' galeria.id %}" class="btn btn-primary">Volver a la Galería</a>
    {% endif %}
    <h2>{{ obra.titulo }}</h2>
    <p>{{ obra.descripcion }}</p>
    <p>Artista: {{ obra.autor.nombreArtista }}</p>
    <p>Precio: {% if obra.precio %}${{ obra.precio }}{% else %}No disponible{% endif %}</p>
    <p>Fecha de Creación: {{ obra.fechaCreacion }}</p>
    {% if obra.vendido %}
      <p>Estado: Vendido</p>
    {% endif %}
    <img src="{{ obra.imagen.url }}" alt="{{ obra.titulo }}" />
  </div>
</div>
<style>
.menu {
  text-align: center; /* Centrar contenido horizontalmente */
}

.center-content {
  background-color: #fff; /* Cambia el color de fondo del contenido */
  text-align: center; /* Centra el contenido horizontalmente */
  padding: 20px; /* Agrega espaciado alrededor del contenido */
}

</style>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/error.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
    <div class="mensaje-error">
        <h1 class="titulo-centrado">¡Error al grabrar la Obra!!!</h1>
        <h2 class="titulo-centrado">El campo Galeria no puede estar vacío!!!.</p>
        <!-- Puedes agregar más contenido personalizado aquí -->
    </div>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/formularioAltaCarrito.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
    <h1 class="titulo-centrado">Alta de Carrito</h1>
    <form action="{% url 'formularioAltaCarrito' %}" method="post" class="text-center">
        {% csrf_token %}
        
        
        <label for="id_comprador">Comprador:</label>
        <select id="id_comprador" name="comprador" required>
            <option value="" disabled selected>Selecciona un comprador</option>
            {% for usuario in usuarios %}
                <option value="{{ usuario.id }}">{{ usuario.nombreUsuario }}</option>
            {% endfor %}
        </select>
        
        
        <div>
            <label for="id_obras">Obras de Arte:</label>
            <select id="id_obras" name="obras"  multiple>
                {% for obra in obras_de_arte %}
                    <option value="{{ obra.id }}">{{ obra.titulo }}</option>
                {% endfor %}
            </select>
        </div>
        
        <button type="submit" class="btn btn-primary mx-auto">Guardar</button>
    </form>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/formularioAltaObraArte1.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
<div class="container mt-4">
    <h1 class="titulo-centrado">Alta de Obra de Arte</h1>
    <form action="{% url 'formularioAltaObraArte1' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_titulo">Título de la Obra de Arte:</label>
            <input type="text" id="id_titulo" name="titulo" maxlength="150" required class="form-control">
        </div>
        
        <div class="form-group">
            <label for="id_descripcion">Descripción de la Obra de Arte:</label>
            <textarea id="id_descripcion" name="descripcion" rows="4" required class="form-control"></textarea>
        </div>
        
        <div class="form-group">
            <label for="id_autor">Autor:</label>
            <select id="id_autor" name="autor" required class="form-control">
                {% for artista in artistas %}
                    <option value="{{ artista.id }}">{{ artista.nombreArtista }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="id_galeria">Galería:</label>
            <select id="id_galeria" name="galeria" required class="form-control">
                {% for galeria in galerias %}
                    <option value="{{ galeria.id }}">{{ galeria.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group">
            <label for="id_precio">Precio:</label>
            <input type="text" id="id_precio" name="precio" maxlength="10" required class="form-control">
        </div>
        
        <div class="form-group">
            <label for="id_fechaCreacion">Fecha de Creación:</label>
            <input type="date" id="id_fechaCreacion" name="fechaCreacion" required class="form-control">
        </div>
        
        <div class="form-group">
            <label for="id_vendido">¿Vendido?</label>
            <input type="checkbox" id="id_vendido" name="vendido" class="form-check-input">
        </div>
        
        <div class="form-group">
            <label for="id_imagen">Imagen:</label>
            <input type="file" id="id_imagen" name="imagen" accept="image/*" required class="form-control-file">
        </div>
        
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/galerias1.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
    <h1 class="titulo-centrado">Listado de Galerias</h1>
    <ul>
        {% for galeria_info_item in galerias_info %}
            <div class="card" style="width: 18rem;">
                <img src="https://www.wallpaperflare.com/static/829/227/702/cat-artwork-eyes-deep-art-wallpaper.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{galeria_info_item.nombre_galeria}}</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="index/" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>    
        {% endfor %}
    </ul>
{% endblock contenidoNuevo %}

AppGaleriaWeb/templates/imagenes.html
<div class="w3-rest">
  <br>
     <div class="w3-row">
         <div class="w3-col s4">
           <img src="/static/images/1.jpg">
         </div>
         <div class="w3-col s4">
           <img src="/static/images/2.jpeg">
         </div>
         <div class="w3-col s4">
           <img src="/static/images/3.jpeg">
         </div>
     </div>
     <div class="w3-row">
         <div class="w3-col s4">
           <img src="/static/images/5.jpeg">
         </div>
         <div class="w3-col s4 bg">
            <img src="/static/images/12.jpeg">
         </div>
         <div class="w3-col s4">
           <img src="/static/images/8.jpeg">
         </div>
     </div>
     <div class="w3-row">
         <div class="w3-col s4">
           <img src="/static/images/7.jpeg">
         </div>
         <div class="w3-col s4">
           <img src="/static/images/10.jpeg">
         </div>
         <div class="w3-col s4">
           <img src="/static/images/9.jpeg">
         </div>
     </div>
</div>

AppGaleriaWeb/templates/registro_exitoso_obra_arte.html
{% extends 'pagina_inicio.html' %}
{% block contenidoNuevo %}
    <h1 class="titulo-centrado">Registro de Obra de Arte Exitoso!!!!</h1>
    
      
{% endblock contenidoNuevo %}